#!/usr/bin/env bash

#    This file is part of libalexandria.
#
#    libalexandria is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    libalexandria is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with libalexandria.  If not, see <http://www.gnu.org/licenses/>.

WORKING_DIR=`pwd`

if [ ! -x "${GIT_COMMAND}" ]; then
	export GIT_COMMAND=`which git`
fi

if [ ! -x "${SLOCCOUNT_COMMAND}" ]; then
	export SLOCCOUNT_COMMAND=`which sloccount`
fi

if [ -z "${SLOCCOUNT_FILE}" ]; then
	export SLOCCOUNT_FILE=${WORKING_DIR}/README.sloc
fi

# Run the SLOC command
${SLOCCOUNT_COMMAND} ${WORKING_DIR}/{android,bindings,dev,fortran,glue,include,tests} > ${SLOCCOUNT_FILE}

# Add the SLOC file
${GIT_COMMAND} add ${SLOCCOUNT_FILE}
