/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_alexandria_functional_RealParameterizedFunction */

#ifndef _Included_lib_alexandria_functional_RealParameterizedFunction
#define _Included_lib_alexandria_functional_RealParameterizedFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_alexandria_functional_RealParameterizedFunction
 * Method:    apply
 * Signature: ()Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_lib_alexandria_functional_RealParameterizedFunction_apply
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
