/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_alexandria_functional_wavelets_Wavelet */

#ifndef _Included_lib_alexandria_functional_wavelets_Wavelet
#define _Included_lib_alexandria_functional_wavelets_Wavelet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_alexandria_functional_wavelets_Wavelet
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_alexandria_functional_wavelets_Wavelet_sync
  (JNIEnv *, jobject);

/*
 * Class:     lib_alexandria_functional_wavelets_Wavelet
 * Method:    benchmark
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_alexandria_functional_wavelets_Wavelet_benchmark
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
