/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_alexandria_pipeline_Aqueduct */

#ifndef _Included_lib_alexandria_pipeline_Aqueduct
#define _Included_lib_alexandria_pipeline_Aqueduct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_alexandria_pipeline_Aqueduct
 * Method:    alloc
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_lib_alexandria_pipeline_Aqueduct_alloc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_alexandria_pipeline_Aqueduct
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_alexandria_pipeline_Aqueduct_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
