/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_alexandria_models_reinforcement_nn_NativeWorker */

#ifndef _Included_lib_alexandria_models_reinforcement_nn_NativeWorker
#define _Included_lib_alexandria_models_reinforcement_nn_NativeWorker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_alexandria_models_reinforcement_nn_NativeWorker
 * Method:    operate
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_lib_alexandria_models_reinforcement_nn_NativeWorker_operate
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
