/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_alexandria_pipeline_Aqueduct_State */

#ifndef _Included_lib_alexandria_pipeline_Aqueduct_State
#define _Included_lib_alexandria_pipeline_Aqueduct_State
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
