/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_alexandria_functions_sigmoid_SigmoidFunction */

#ifndef _Included_lib_alexandria_functions_sigmoid_SigmoidFunction
#define _Included_lib_alexandria_functions_sigmoid_SigmoidFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_alexandria_functions_sigmoid_SigmoidFunction
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_alexandria_functions_sigmoid_SigmoidFunction_sync
  (JNIEnv *, jobject);

/*
 * Class:     lib_alexandria_functions_sigmoid_SigmoidFunction
 * Method:    benchmark
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_alexandria_functions_sigmoid_SigmoidFunction_benchmark
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
