/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_alexandria_proof_POC */

#ifndef _Included_lib_alexandria_proof_POC
#define _Included_lib_alexandria_proof_POC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_alexandria_proof_POC
 * Method:    println
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lib_alexandria_proof_POC_println
  (JNIEnv *, jclass, jstring);

/*
 * Class:     lib_alexandria_proof_POC
 * Method:    initialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_alexandria_proof_POC_initialize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_alexandria_proof_POC
 * Method:    finalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_alexandria_proof_POC_finalize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
